name: Machine Learning CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MLflow & Dependencies
        run: |
          pip install mlflow scikit-learn pandas

      - name: Run MLflow Project
        run: |
          mlflow run MLProject_Folder/ --no-conda # Menjalankan training
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }} # Jika pakai DagsHub

      # --- BAGIAN ADVANCE: Build Docker Image ---
      - name: Build Docker Image
        run: |
          mlflow models build-docker -m "runs:/<RUN_ID>/model" -n "my-ml-model"
        # Catatan: RUN_ID bisa didapat secara dinamis dari output script sebelumnya
